---
- hosts: dev
  become: True
  tasks:
    - name: Update package repository
      yum:
        update_cache: yes

    - name: Install dependencies for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Remove conflicting runc package
      yum:
        name: runc
        state: absent

    - name: Add Docker repository
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install containerd.io
      yum:
        name: containerd.io
        state: present

    - name: Install docker
      yum:
        name: docker-ce
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install python3 pip
      yum:
        name: python3-pip
        state: present

    - name: Install docker python module
      pip:
        name: docker
        state: present

    - name: Start the container
      docker_container:
        name: demoapp
        image: "duogwas/demoapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080